### ISSUE TITLE
Language pages need updated logos.

### ISSUE THREAD

**Issue by ioquatix** [ioquatix/programming.dojo.net.nz#26]
The language page doesn't seem to have the logo. Maybe it's a CSS bug or the URL is not being generated correctly.

<img width="992" alt="image" src="https://user-images.githubusercontent.com/30030/72864942-c45c4400-3d3a-11ea-8f66-8bcd7f752e8a.png">

Here is the CSS:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/30030/72864947-ca522500-3d3a-11ea-911a-fbf3dd8bdc7a.png">

Maybe something wrong with `url()`?

**Comment by courtneycb** [comment]
Can confirm the URL is not being generated correctly. The problematic code is on line 9 of /pages/languages/_heading.xnode 

Since the logos are now a mix of PNG and SVG type we need to generate the logo file path without hard coding the extension. The previous working version hard coded the extension (the current change in master does not hard code it but it is not working).

**Comment by ioquatix** [comment]
I suggest we just put the path for the logo in place of `filetype:` in the `links.yaml` file and use that directly.

**Comment by courtneycb** [comment]
Will implement the change.

**Comment by ioquatix** [comment]
Fixed in #27
